# -*- coding: utf-8 -*-
"""baby

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q5nJ8xidFnePggvE3ngxq8iEr2NtGBpb
"""

#storing the input of the birth year of the user as a variable
birth_year = input("PLease enter the year you were born: ")

#converting the string variable in to an integer
birth_year = int(birth_year)

#in order for the program to determine the age of the user it needs the current year
current_year = 2022

#with the current year, it will calculate the difference, x, between it 
#and the birth year of the user. 
#Alternatively there could be another input for the current year
x = 2022 - birth_year

#condition statement if the user's birth year and current year have a difference
#equal or higher of the number 18
if x >= 18:
  print("Congrats you are old enough.")