# -*- coding: utf-8 -*-
"""bmi_task

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-WlE3807cYxdHPrz1L07GexJGapkTV3Q
"""

#naming variables that store the user's input weight and height value
weight = float(input("Please enter your weight in kg: "))
height = float(input("Please enter your age in m: "))

#BMI calculation with the given formula
BMI = weight/((height)*(height))

#conditional statements based on the calculated BMI of the user
if BMI >= 30:
    print("Your BMI indicates that you are obese.")
elif BMI >= 25:
    print("Your BMI indicates that you are overweight.")
elif BMI >= 18.5:
    print("Your BMI indicates that you are normal.")
elif BMI <= 18.5:
    print("Your BMI indicates that you are underweight.")