# -*- coding: utf-8 -*-
"""control

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QezzUN_mxqAGlmLkql9k2QT5EMeDyLs_
"""

#Asking the user's age and storing it in a variable
age = int(input("Please enter your age: "))

#condition statement that checks if the user is old enough
if age >= 18:
    print("You're old enough!")
elif age > 16 and age < 18:
    print("Almost there!")
else:
    print("You're just too young!")