# -*- coding: utf-8 -*-
"""courier

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11su63cvRcQ1YanhhmcRnFFkOubhVwuJE
"""

#starting inputs
package_price = int(input("Please enter the price of the product you want to purchase: "))
distance = int(input("Please enter the total distance of the delivery in km: "))

#assigning starting values to variables
total = package_price
print(total)
air = 0.36*distance
freight = 0.25*distance
full = 50.00
limited = 25.00
gift = 15.00
no_gift = 0.00
priority = 100.00
standard = 20.00

#getting inputs to calculate total
delivery_way = input("How would you like for your package to be delivered? "
    "Type 1 for Air, Type 2 for Freight: ")
insurance = input("What type of insurance would you like on your package? "
    "Type 1 for Full, Type 2 for Limited: ")
gift_option = input("Would you like to add the gift option? "
    "Type 1 for Yes, Type 2 for No: ")
delivery_type = input("Select a delivery type: "
"Type 1 for Priority, Type 2 for Standard: ")

#conditional statement based on delivery way
if delivery_way == "1":
    print("Delivery will cost {}." .format(air))
    total = total + air #alternative: total += air
else:
    print("Delivery will cost {}." .format(freight))
    total = total + freight
print("Your total so far is {}." .format(total))

#conditional statement based on insurance type
if insurance == "1":
    print("Insurance will cost {}." .format(full))
    total = total + full
else:
    print("Insurance will cost {}." .format(limited))
    total = total + limited
print("Your total so far is {}." .format(total))

#conditional statement based on gift option
if insurance == "1":
    print("The Gift option will cost {}." .format(gift))
    total = total + full
else:
    print("The no Gift Option will cost {}." .format(no_gift))
    total = total + limited
print("Your total so far is {}." .format(total))

#conditional statement based on delivery type
if delivery_type == "1":
    print("The selected delivery type will cost {}." .format(priority))
    total = total + priority
else:
    print("The selected delivery type will cost {}." .format(standard))
    total = total + standard
print("Your total so far is {}." .format(total))

total = total
print("The total price of the package is {}." .format(total))