# -*- coding: utf-8 -*-
"""errors

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KnDauZWuNF4KHHj7JQiX6RsM-dS3Up7m
"""

#errors1
print("Welcome to the error program") #Syntax Error, print was missing the brackets
print("\n") #Syntax Error, print was missing the brackets. Runtime Error, unexpected indent

ageStr = "24" #I'm 24 years old. 
#Runtime Error, unexpected indent. Runtime Error: name 'ageStr' is not defined,
#the string cant later be turned in to an integer if its a whole sentence

age = int(ageStr) #Runtime Error, unexpected indent
print("I'm " + ageStr + "years old.") #Runtime , unexpected indent.
#Runtime Error, can only concatenate str (not "int") to str, added the string instead
three = "3" #Runtime Error, unexpected indent

answerYears = age + int(three) #Runtime Error, unexpected indent.
#Three needs to be turned into an integer first in order to be added with another integer

print("The total number of years:" + str(answerYears))
#Syntax Error, print was missing the brackets.
#Logical Error, we want it to print the number stored in the variable answerYears not the word.

answerMonths = answerYears * 12 #Runtime Error: name 'answer' is not defined, 
#Runtime Error: name 'answer' is not defined, word answer replaced with answer Years

print("In 3 years and 6 months, I'll be " + str(answerMonths) + " months old") 
#SyntaxError, print was missing the brackets.
#Runtime Error: can only concatenate str (not "int") to str

#errors2
animal = "Lion" #Runtime Error: name 'Lion' is not defined, needed to add ""
animal_type = "cub"
number_of_teeth = 16

full_spec = f"This is a {animal}. It is a {animal_type} and it has {number_of_teeth} teeth."
#Logical Error, we want it to print the information that are stored in the variables.

print(full_spec) #Syntax Error: Missing parentheses in call to 'print'