# -*- coding: utf-8 -*-
"""full_name

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EeK6P-J51OK2L3kHng7R1cOHYPInzjVn
"""

full_name = input("Enter your full name: ") #asks user to enter their full name
char_count = int(len(full_name)) #calculating the characters of the full name
if char_count == 0:
  print("You haven’t entered anything. Please enter your full name.")

if char_count < 4:
  print("You have entered less than 4 characters.Please make sure that you have entered your name and surname.")

if char_count > 25:
  print("You have entered more than 25 characters.Please make sure that you have only entered your full name.")

if char_count > 4 and char_count < 25: #https://learnpython.com/blog/multiple-conditions/
  print ("Thank you for entering your name.")