# -*- coding: utf-8 -*-
"""manipulation

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c9ztZqwelUCHZGncn04i6MuR10WHjt1S
"""

str_manip = input("Enter a sentence: ") #asks user to input a sentence
print(len(str_manip)) #prints the amount of letters of the strip
print(str_manip[-1]) #prints the last letter of the string saved in str_manip
last_letter = str_manip[-1] #the last letter of str_manip is stored in this variable
print(str_manip.replace(last_letter, "@")) #prints the srting saved in str_manip when the last letter is replaced by "@"
print(str_manip[:-4:-1]) #prints last 3 characters in str_manip backwards

#the first three letters and the last two are stored in a variable
five_letter_word = str_manip[0] + str_manip[1] + str_manip[2] + str_manip[-2] + str_manip[-1]

print(five_letter_word)

#the space in between words is replaced by "Newline"
print(str_manip.replace(" ", "\n"))