# -*- coding: utf-8 -*-
"""task3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F6zutwDlDLeHlxBuEvJAassFfdag5Fjl
"""

#Asking the user to enter the values in variables, we want integers in this case
#not a string, so we use int() before the input
swimming=int(input("Enter the time taken, in minutes, for the athlete to complete the sport: "))
cycling=int(input("Enter the time taken, in minutes, for the athlete to complete the sport: ")) 
running=int(input("Enter the time taken, in minutes, for the athlete to complete the sport: "))

#calculating the total time taken for the athlete to complete the sport
total = swimming + cycling + running

#stating the qualofying time that will be used to determine the award
qualifying_time = 100 #minutes

#conditional statements that determine the award of the athlete, 
#depending if the given time is within the boundaries of the award

#within the qualifying time
if total <= qualifying_time:
    print("Award: Provincial Colours")

#within 5 min of the qualifying time
if total > qualifying_time and total <= (qualifying_time + 5):
    print("Award: Provincial Half Colours")

#within 5 and 10 min of the qualifying time
if total > (qualifying_time + 5) and total <= (qualifying_time + 10):
    print("Award: Provincial Scroll")

#more than 10 min of the qualifying time
if total > (qualifying_time + 10): 
    print("No Award")