# -*- coding: utf-8 -*-
"""task1, 13

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LIu9PJI01yHeYG7pXKE9et92KMPwB1kt
"""

#Asks the user to input a radonm number, int() is used so the input wont be a string
x = int(input("Enter a number: "))

#For loop used to repeat multiplying the input number in the range between 1 and 13
for y in range(1,13):
    print(str(x) + "*" + str(y) + "=" + str(x*y)) #prints the multiplication table