# -*- coding: utf-8 -*-
"""task2, 13

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tdp26fYIRSjLxt_9kZ3eRYOTmG7iGoRK
"""

#Asks the user to input the year and the number of years they want to check
year = int(input("What year do you want to start with? ")) -1
number = int(input("How many years do you want to check? "))

#for loop that repeatedly checks which years are leap years, the range is the input year
#and the end year is the intial year when the number of input years are added to it
for number in range(year, year+number):
    year+=1 #ensures that every year is checked
    if year %4 == 0: #checks if the years are multiples of 4
        print("{} is a leap year".format(year))
    else: #if they arent multiples of 4 it prints the following line
        print("{} isn't a leap year".format(year))