# -*- coding: utf-8 -*-
"""task 3, 13

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12805iIoD4IJ2lrE0gaVQNGZUzAhRLgZt
"""

#1
i = 21 #we want the algorytm to count from 20 so we set i as 21
while i > 0:
    i-=1 #since its a cowntdown we set it in a way that the algorithm will go down by one each time
    print(i)

#2
#even numbers are divided by 2 and have remainder 0, 
#this algorithm prints the numbers in i when the remainder is 0
i = 0
for i in range(1,20):
    if i %2 != 0: 
        print(i)

#3
#got help from:
#https://stackoverflow.com/questions/32981772/produce-the-following-output-for-and-while-loops-in-python
i = 0
for i in range(1,6): #we want 5 rows, so range is from 1 to 6
    i += 1
    print("*"*(i-1))
    
#4
#gcd: "the largest positive integer that divides each of the integers" - wikipedia
#Asking user to store two integers in the below variables
integer1=int(input(""))
integer2=int(input(""))
gcd = i = 1
#to set the range of gcd values we need to find the smallest number from input integers,
#this is because the gcd value won't be greater than the smallest input number
#so there is no need for the range to include greater numbers
if integer1 < integer2:
    smallest = integer1
else:
    smallest = integer2
for i in range(smallest, 1):
    if integer1 %gcd ==0 and integer2 %gcd ==0: #checks for which value of i both integers 
    #can be devided with producing a remainder of 0
        print(gcd)