# -*- coding: utf-8 -*-
"""task2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1upFUZoKXNhVnSPj_uJdIkVvjO5R9a8Tf
"""

import math

#Asking user to input the shape of the building as a string in a variable
shape = input("Enter the shape of the building (square, rectangular or round: ")

#Using conditional statements the algorithm states which values or dimensions
#are needed in order for the area of the building to be calculated.
#My algorithm asks the user to input the value of the dimensions after it displays
#which dimensions are needed.
#it also calculates the area of the shapes based on the users input 
#and the area formulae given by the exercise
if shape == "square" or shape == "Square" or shape == "SQUARE":
    print("The square's length dimentions are needed.")
    sq_length=int(input("Enter the value, as an integer, of the length of the square: "))
    sqr = sq_length**2
elif shape == "rectangular" or shape == "Rectangular" or shape == "RECTANGULAR":
    print("The rectangle's length and width dimentions are needed.")
    rec_length=int(input("Enter the value, as an integer, of the length of the rectangle: "))
    width=int(input("Enter the the value, as an integer, of the width of the rectangle: "))
    rec = rec_length*width
elif shape == "round" or shape == "Round" or shape == "ROUND":
    print("The circle's radius is needed.")
    radius=int(input("Enter the value, as an integer, of the radius of the circle: "))
    circ = math.pi*(radius**2)

#Conditional statement that displays the calculated area of the building
if shape == "square" or shape == "Square" or shape == "SQUARE":
    print("The area of the building is {}." .format(sqr))
elif shape == "rectangular" or shape == "Rectangular" or shape == "RECTANGULAR":
    print("The area of the building is {}." .format(rec))
elif shape == "round" or shape == "Round" or shape == "ROUND":
    print("The area of the building is {}." .format(circ))