# -*- coding: utf-8 -*-
"""while

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lbijY_ls1DAAhz9aZTEQd76UsKCTn5zl
"""

#Asking user to input a number, int() is used to ensure the variable is an integer
number = int(input("Enter a number:"))
i = 1 #Algoritm starts counting the first name from number 1
total = 2 #Algorithm counts with starting point as no 2 because when the user inputs -1
           #we want the total to start adding numbers starting from the first input not from 0 

#When input isn't == to -1, the while loop repeats asking the user to input numbers
while number != -1:
    number = int(input("Enter a number:"))
    i += 1 #keeps track of the no of the input numbers by adding 1 for every number
    total += number #adds the input numbers together

#Prints the average of input numbers minus the -1, therefore i-1 is used
average = total/(i-1)
print(total)

#-1 is a signal for the algorithm to stop asking the user to enter a number
#thats why we subtract it

#https://stackoverflow.com/questions/10291619/calculating-average-in-python-using-while-loop
#got help from the above link for the "total" line